tasks:
  - init: "chmod 0755 ./extension/build.sh && cd extension && ./build.sh"
    command: "gp await-port 23000 && code --install-extension ../opensearch-vscode-extension-1.0.0.vsix"
  - init: "cd demo && docker-compose pull"
  - command: "cd demo && docker-compose up"
  - init: "./demo/check-dashboards.sh"
    command: "touch ready.txt"

ports:
  - port: 5601
    onOpen: ignore
  - port: 9200
    onOpen: ignore
  - port: 9600
    onOpen: ignore