repos:
    # MIT
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files


    # MIT
-   repo: https://github.com/dtaivpp/commit-msg-regex-hook
    rev: v0.2.1
    hooks:
        -   id: commit-msg-regex-hook
            args: ["--pattern='Signed-off-by: .* <.*@.*\\..*>'",
                   "--failure_message='Ensure you are signing the DCO\n  Do this by adding -s to your commit: git commit -s -m <commit message>'"]
            stages: [commit-msg]


    # Apache 2.0
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
    -   id: detect-secrets
        args: ["scan"]


    # MIT
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
        -   id: docker-compose-check

-   repo: local
    hooks:
    -   id: run_cluster_bootstrap_test
        name: run cluster bootstrap test
        entry: python ./demo/test/test_cluster_bootstrap.py
        language: python
        always_run: true
        verbose: true

-   repo: local
    hooks:
    -   id: run_ingestion_test
        name: run ingestion test
        entry: python ./demo/test/test_ingestion.py
        language: python
        always_run: true
        verbose: true

-   repo: local
    hooks:
    -   id: run_integration_test
        name: run integration test
        entry: python ./demo/test/test_integration.py
        language: python
        always_run: true
        verbose: true

-   repo: local
    hooks:
    -   id: run_query_test
        name: run query test
        entry: python ./demo/test/test_query_pipeline.py
        language: python
        always_run: true
        verbose: true

-   repo: local
    hooks:
    -   id: run_util_test
        name: run util test
        entry: python ./demo/test/test_util.py
        language: python
        always_run: true
        verbose: true

-   repo: local
    hooks:
    -   id: run_ingestion_test
        name: run ingestion test
        entry: python ./demo/test/test_ingestion.py
        language: python
        always_run: true
        verbose: true
