# pyproject.toml

# yapf can be installed using 'pip install yapf'
[tool.yapf]
column_limit = 100
based_on_style = "pep8"
indent_width = 2
continuation_indent_width = 2
join_multiple_lines = true
indent_dictionary_value = true
coalesce_brackets = true
each_dict_entry_on_separate_line = true
align_closing_bracket_with_visual_indent = true
