version: '3'

services:
  fluentd:
    build:
      context: ./fluentd
      args:
        - FLUENTD_VERSION=${FLUENTD_VERSION}
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - opensearch-net
    depends_on:
      - opensearch
      - kafka

  zookeeper:
   image: docker.io/bitnami/zookeeper:${ZOOKEEPER_VERSION}
   container_name: zookeeper
   ports:
     - "2181:2181"
   volumes:
     - "zookeeper_data:/bitnami"
   environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
   networks:
     - opensearch-net

  kafka:
    image: docker.io/bitnami/kafka:${KAFKA_VERSION}
    container_name: kafka
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - "kafka_data:/bitnami"
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - opensearch-net

volumes:
  zookeeper_data:
  kafka_data:
